language: java
jdk:
- openjdk7
deploy:
  provider: heroku
  api_key:
    secure: JRKotKDN8Y2Xs57foWiVHw7QF44ie+eUaczOow9GsP0vH6nLJGn4w2dRd5gjQuluSAu+qouKQE64VSPcuah+159L6CLsQJRCGm1Ex9UHDkeMgs2hO29/Sz6xKqxCJn9w8QW16bFF1s0CVwSo72zyG7xk6JkhH+kFVi8XYa24Fz0=
  app: onsdigital
  on:
    repo: ONSdigital/tredegar
