---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-node-java
    tag: 3.8.8-eclipse-temurin-8-node-22

inputs:
  - name: babbage

outputs:
  - name: build

run:
  path: babbage/ci/scripts/build.sh
